use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'NiceTable_Example' do
  pod 'NiceTable', :path => '../'

  target 'NiceTable_Tests' do
    inherit! :search_paths
  end
end
